### PR TITLE
Grafana 7 compatibility

### PR DESCRIPTION
**Pull request by AnushaBoggarapu**
- font color selection input control styles fix 
 - Traffic lights overflow issue fix in case of panel view and edit. Due to grafana 7 changes
 - The link form is not being shown on render as link check box enable\disable. This is due to the grafana 7 changes of visualization plugin layout.
- Image renderer latest tested and certified

Bumped version to 1.4.7

### CODE REVIEW

**Comment by snuids** [comment]
Nice job,

I have two other plugins if you are interested:

* https://github.com/snuids/grafana-svg-panel
* https://github.com/snuids/grafana-radar-panel

Cheers,


Thanks,

**Comment by snuids** [comment]
I am waiting for the approval of my svg panel. Once it is done, I will push the new version.

**Comment by AnushaBoggarapu** [comment]
I forgot pushing the readme.md file. Please add the necessary when releasing the image.
Image renderer support
Grafana 7 compatibility

And yes looks like the svg panel is useful for us. But we would need drilldown on it. I will look into it

**Comment by AnushaBoggarapu** [comment]
Did you release the new version, If not can you do the same.

**Comment by snuids** [comment]
I merged your code, but did not publish it in the grafana plugin directory because I am still waiting for their approval on the svg panel. =>[PR]( https://github.com/grafana/grafana-plugin-repository/pull/733)

If I update the version in the plugin directory, my pull request will have two updates which will probably mess with their validation process.

**Comment by AnushaBoggarapu** [comment]
I see the PR is merged so did you release a new version of traffic light plugin?

**Pull request merged**
