### PR TITLE
Threshold error message correction

### PR DESCRIPTION
**Pull request by AnushaBoggarapu**

### CODE REVIEW

**Comment by snuids** [comment]
Thanks for the fixes

**Comment by AnushaBoggarapu** [comment]
When can u release this plugin? It is getting difficult for us to maintain the code fork separately

**Comment by snuids** [comment]
I am quite busy for the moment, and the process of releasing a plugin in Grafana is time consuming. (https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/)

If you have time to do it and interested in doing it, I can invite you to this repository and you can do everything by yourself.

Cheers,

**Comment by AnushaBoggarapu** [comment]
Yes please send me the invite and i will help release the plugin

**Pull request merged**
