### PR TITLE
Add font color

### PR DESCRIPTION
**Pull request by acceleris-buergisserp**

### CODE REVIEW

**Comment by snuids** [comment]
@acceleris-buergisserp 

Looks good to me except that you should update the version number in the package.json and plugin.json to 1.4.6

Thanks for the help,

Arnaud

**Comment by snuids** [comment]
Thanks,

Take care

**Comment by acceleris-buergisserp** [comment]
@snuids With pleasure !
Can you update the Grafana plugins portal accordingly please?

Cheers

**Comment by snuids** [comment]
Done but it can take time before they accept my PR.

**Pull request merged**
